# JPA properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Datasource properties
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/workflow
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

hibernate.show_sql=false
logging.level.org.flywaydb=ERROR
logging.level.com.zaxxer.hikari=ERROR

# CORS Config
cors.allowedOrigins=http://localhost:3000
cors.allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#cors.allowedHeaders=Accept,Authorization,Content-Type
cors.allowedHeaders=*
cors.allowCredentials=true
cors.maxAge=600

# Security Config
security.protected-urls=/secure/**, /api/private/**
security.unprotected-urls=/**, /api/public/**