server:
  port: 9091

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  server:
    compression:
      enabled: true
  logging:
    level:
      org.hibernate.SQL: DEBUG

flyway:
  url: ${DB_URL}
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  locations: classpath:db/migration