CREATE TABLE tenant (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_name varchar(100) NOT NULL,
  address varchar(300) NOT NULL,
  city varchar(200) NOT NULL,
  state varchar(200) NOT NULL,
  country_id int(10) DEFAULT NULL,
  pin_code varchar(10) DEFAULT NULL,
  phone_number varchar(40) NOT NULL,
  email_id varchar(100) DEFAULT NULL,
  activation_date datetime NOT NULL,
  expiry_date datetime NOT NULL,
  grace_period int(10) DEFAULT NULL COMMENT 'Number of remaining days.',
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id) USING BTREE
);

CREATE TABLE company_type (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  type varchar(40) NOT NULL,
  description varchar(50) DEFAULT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uk_company_type_uuid (uuid),
  KEY tenant_id (tenant_id),
  CONSTRAINT company_type_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE company (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(40) NOT NULL,
  company_type_id int(10) NOT NULL,
  company_name varchar(100) NOT NULL,
  CIN varchar(40) DEFAULT NULL,
  GSTIN varchar(40) DEFAULT NULL,
  TAN varchar(40) DEFAULT NULL,
  PAN varchar(20) DEFAULT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id) USING BTREE,
  UNIQUE KEY UUID (uuid),
  KEY fk_company_tenant (tenant_id),
  KEY fk_company_company_type (company_type_id),
  CONSTRAINT fk_company_company_type FOREIGN KEY (company_type_id) REFERENCES company_type (id),
  CONSTRAINT fk_company_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);


CREATE TABLE address_type (
  id int(11) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  type varchar(40) NOT NULL,
  description varchar(50) DEFAULT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uk_address_type_uuid (uuid),
  KEY tenant_id (tenant_id),
  CONSTRAINT address_type_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE address (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  company_id int(10) NOT NULL,
  address_type_id int(10) NOT NULL,
  address_line1 varchar(100) DEFAULT NULL,
  address_line2 varchar(100) DEFAULT NULL,
  address_line3 varchar(100) DEFAULT NULL,
  city varchar(200) DEFAULT NULL,
  state_code varchar(50) NOT NULL,
  country_code varchar(50) NOT NULL,
  pin_code varchar(50) NOT NULL,
  work_phone varchar(20) DEFAULT NULL,
  fax varchar(40) DEFAULT NULL,
  primary_phone_number varchar(20) DEFAULT NULL,
  alternate_phone_number varchar(20) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  website varchar(100) DEFAULT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id) USING BTREE,
  UNIQUE KEY uuid (uuid),
  CONSTRAINT address_company_id_caifk_1 FOREIGN KEY (company_id) REFERENCES company (id),
  CONSTRAINT address_address_type_id_aatifk_1 FOREIGN KEY (address_type_id) REFERENCES address_type (id)
);

CREATE TABLE role_type (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  name varchar(100) NOT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uuid (uuid),
  KEY tenant_id (tenant_id),
  CONSTRAINT role_type_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE user (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  role_id int(10) NOT NULL,
  name varchar(100) NOT NULL,
  user_name varchar(100) NOT NULL UNIQUE,
  password varchar(50) NOT NULL,
  salt varchar(50) NOT NULL,
  mobile_number varchar(20) NOT NULL,
  email_id varchar(50) NOT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uuid (uuid),
  KEY tenant_id (tenant_id),
  KEY role_id (role_id),
  CONSTRAINT tenant_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id),
  CONSTRAINT role_type_role_ibfk_1 FOREIGN KEY (role_id) REFERENCES role_type (id)
);

CREATE TABLE additional_charges (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  extra_mm decimal(10,2) DEFAULT NULL,
  insurance decimal(10,2) DEFAULT NULL,
  admin_charges decimal(10,2) DEFAULT NULL,
  forwarding_charges decimal(10,2) DEFAULT NULL,
  gst decimal(10,2) DEFAULT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
    PRIMARY KEY (id),
  KEY tenant_id (tenant_id),
  CONSTRAINT additional_charges_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE confirm_through (
   id int(10) NOT NULL AUTO_INCREMENT,
   uuid varchar(36) NOT NULL,
   tenant_id int(10) NOT NULL,
   name varchar(50) DEFAULT NULL,
   created_dttm datetime DEFAULT NULL,
   last_updated_dttm datetime DEFAULT NULL,
   created_by varchar(100) DEFAULT NULL,
   last_updated_by varchar(100) DEFAULT NULL,
   is_active boolean DEFAULT 1,
   PRIMARY KEY (id) USING BTREE,
   CONSTRAINT confirm_through_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
 );

CREATE TABLE glass_specification (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  name varchar(100) NOT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uuid (uuid),
  KEY tenant_id (tenant_id),
  CONSTRAINT glass_specification_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE glass_thickness (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  name varchar(100) NOT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uuid (uuid),
  KEY tenant_id (tenant_id),
  CONSTRAINT glass_thickness_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE glass_type (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  glass_name varchar(100) NOT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uuid (uuid),
  KEY tenant_id (tenant_id),
  CONSTRAINT glass_type_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE pi_type (
	id INT(10) NOT NULL AUTO_INCREMENT,
	uuid VARCHAR(36) NOT NULL,
	tenant_id INT(10) NOT NULL,
	pi_type_name VARCHAR(10) NOT NULL,
	  created_dttm datetime DEFAULT NULL,
      last_updated_dttm datetime DEFAULT NULL,
      created_by varchar(100) DEFAULT NULL,
      last_updated_by varchar(100) DEFAULT NULL,
      is_active boolean DEFAULT 1,
	PRIMARY KEY (id) USING BTREE,
	UNIQUE INDEX uk_pi_type_uuid (uuid) USING BTREE,
	INDEX tenant_id (tenant_id) USING BTREE,
	CONSTRAINT pi_type_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE pro_forma_invoice (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  firm_id int(10) NOT NULL,
  id_bill_to int(10) NOT NULL,
  id_ship_to int(10) NOT NULL,
  pi_type_id int(10) NOT NULL,
  confirm_through_id int(10) DEFAULT NULL,
  pi_number varchar(10) NOT NULL,
  invoice_date datetime NOT NULL,
  pro_forma_invoice_amount double DEFAULT NULL,
  service_rate_invoice_amount double DEFAULT NULL,
  basic_amount double DEFAULT NULL,
  admin_charges double DEFAULT NULL,
  insurance_percent float DEFAULT NULL,
  insurance_percent_amount float DEFAULT NULL,
  urgency_percent float DEFAULT NULL,
  urgency_percent_amount float DEFAULT NULL,
  other_charges double DEFAULT NULL,
  transport_charges double DEFAULT NULL,
  gst_charges float DEFAULT NULL,
  grand_total float DEFAULT NULL,
  round_off_amount float DEFAULT NULL,
  payable_amount float DEFAULT NULL,
  previous_balance float DEFAULT NULL,
  adjustment_amount int(10) DEFAULT NULL,
  status varchar(50) DEFAULT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id) USING BTREE,
  UNIQUE KEY uk_pro_forma_invoice_uuid (uuid),
  KEY tenant_id (tenant_id),
  KEY FK_pro_forma_invoice_pi_type (pi_type_id) USING BTREE,
  KEY FK_pro_forma_invoice_confirm_through (confirm_through_id) USING BTREE,
  CONSTRAINT pro_forma_invoice_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE pro_forma_invoice_item (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  pro_forma_invoice_id int(10) NOT NULL,
  glass_type_id int(10) NOT NULL,
  glass_specification_id int(10) NOT NULL,
  glass_thickness_id int(10) NOT NULL,
  width_inch decimal(20,6) DEFAULT NULL,
  width_measurement decimal(20,6) DEFAULT NULL,
  width_measurement_label varchar(20),
  actual_width decimal(20,6) DEFAULT NULL,
  chargable_width decimal(20,6) DEFAULT NULL,
  height_inch decimal(20,6) DEFAULT NULL,
  height_measurement decimal(20,6) DEFAULT NULL,
  height_measurement_label varchar(20),
  actual_height decimal(20,6) DEFAULT NULL,
  chargable_height decimal(20,6) DEFAULT NULL,
  extra_mm decimal(20,6) DEFAULT NULL,
  quantity int(10) DEFAULT NULL,
  unit_value decimal(20,6) DEFAULT NULL,
  rate_per_unit decimal(20,6) DEFAULT NULL,
  unit_measurement_label varchar(20),
  amount decimal(20,6) DEFAULT NULL,
  `optimize_bucket` int(5) DEFAULT 0,
  `cutting_bucket` int(5) DEFAULT 0,
  `toughen_bucket` int(5) DEFAULT 0,
  `dispatch_bucket` int(5) DEFAULT 0,
  `optimize_completed` int(5) DEFAULT 0,
  `cutting_completed` int(5) DEFAULT 0,
  `toughen_completed` int(5) DEFAULT 0,
  `dispatch_completed` int(5) DEFAULT 0,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id) USING BTREE,
  UNIQUE KEY uk_pro_forma_invoice_item_uuid (uuid),
  KEY tenant_id (tenant_id),
  KEY FK_pro_forma_invoice_item_pro_forma_invoice (pro_forma_invoice_id) USING BTREE,
  KEY FK_pro_forma_invoice_item_glass_type (glass_type_id) USING BTREE,
  KEY FK_pro_forma_invoice_item_glass_specification (glass_specification_id) USING BTREE,
  KEY FK_pro_forma_invoice_item_glass_thickness (glass_thickness_id) USING BTREE,
  CONSTRAINT pro_forma_invoice_item_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE `service_rate_invoice` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
     uuid varchar(36) NOT NULL,
	`pro_forma_invoice_id` INT(10) NOT NULL,
	`service_rate_id` INT(10) NOT NULL,
	`quantity` INT(10) NOT NULL,
	`rate` decimal(10,2) NOT NULL,
	`total` decimal(10,2) NOT NULL,
	 created_dttm datetime DEFAULT NULL,
     last_updated_dttm datetime DEFAULT NULL,
     created_by varchar(100) DEFAULT NULL,
     last_updated_by varchar(100) DEFAULT NULL,
     is_active boolean DEFAULT 1,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `uk_service_rate_invoice_uuid` (`uuid`) USING BTREE,
	INDEX `FK_service_rate_invoice_pro_forma_invoice` (`pro_forma_invoice_id`) USING BTREE,
	INDEX `FK_service_rate_invoice_service_rate` (`service_rate_id`) USING BTREE,
	CONSTRAINT `service_rate_invoice_invoice_ibfk_1` FOREIGN KEY (`pro_forma_invoice_id`) REFERENCES `pro_forma_invoice` (`id`)
);


CREATE TABLE service_rate (
  id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  name varchar(255) NOT NULL,
  rate decimal(10,2) NOT NULL,
  created_dttm datetime DEFAULT NULL,
  last_updated_dttm datetime DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  last_updated_by varchar(100) DEFAULT NULL,
  is_active boolean DEFAULT 1,
  PRIMARY KEY (id) USING BTREE,
  KEY tenant_id (tenant_id),
  CONSTRAINT service_rate_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE status (
  status_id int(10) NOT NULL AUTO_INCREMENT,
  uuid varchar(36) NOT NULL,
  tenant_id int(10) NOT NULL,
  name varchar(100) NOT NULL,
  is_active tinyint(1) DEFAULT 1,
  PRIMARY KEY (status_id),
  UNIQUE KEY uuid (uuid),
  KEY tenant_id (tenant_id),
  CONSTRAINT status_tenant_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE TABLE work_order (
   id int(10) NOT NULL AUTO_INCREMENT,
   uuid varchar(36) NOT NULL DEFAULT (UUID()),
   proforma_invoice_id int(10) NOT NULL,
   tenant_id int(10) NOT NULL,
   firm_id int(10) NOT NULL,
   created_dttm datetime DEFAULT NULL,
   last_updated_dttm datetime DEFAULT NULL,
   created_by varchar(100) DEFAULT NULL,
   last_updated_by varchar(100) DEFAULT NULL,
   is_active boolean DEFAULT 1,
   PRIMARY KEY (id) USING BTREE,
   CONSTRAINT work_order_tenant_ibfk_1
   FOREIGN KEY (tenant_id) REFERENCES tenant (id),
   FOREIGN KEY (proforma_invoice_id) REFERENCES pro_forma_invoice (id),
   FOREIGN KEY (firm_id) REFERENCES company (id)
 );
