# App global config
#server.servlet.context-path=/api

#Database config
spring.datasource.url=jdbc:mariadb://localhost:3306/workflow
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.messages.basename=errors

# CORS Config
cors.allowedOrigins=http://localhost:3000
cors.allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#cors.allowedHeaders=Accept,Authorization,Content-Type
cors.allowedHeaders=*
cors.allowCredentials=true
cors.maxAge=600

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhijitsalunkhe4075@gmail.com
spring.mail.password=ciwl bwhw xiwa apje
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#image storage config
image.upload-directory.base=/opt/sowermate_apps/ecom_prod_imgs
image.upload-directory.party-docs=party-docs
image.upload-directory.user-docs=user-docs
image.upload-directory.super-category=super-category
image.upload-directory.category=category
image.upload-directory.sub-category=sub-category
image.upload-directory.product-images=product-images
image.upload-directory.profile-images=profile-images
image.public-url.base=https://qa-ecommerce.sowermate.com/imgs/

#pdf storage config
pdf.upload-directory.base=/opt/sowermate_apps/ecom_prod_pdfs
pdf.upload-directory.party-docs=party-docs
pdf.upload-directory.user-docs=user-docs
pdf.upload-directory.product-invoices=product-invoices

# pdf.upload-directory.base=/home/sborage1/Work/pdf/
# pdf.upload-directory.party-docs=wf
# pdf.upload-directory.user-docs=pi
# pdf.upload-directory.product-invoices=target
pdf.public-url.base=https://qa-ecommerce.sowermate.com/pdfs/

#logging.level.org.springframework=DEBUG

# Authentication
authentication.jwt.token.secret=studenttrackersecretkey1234567890studenttrackersecretkey1234567890studenttrackersecretkey1234567890
authentication.jwt.accessToken.expiry=86400000
authentication.jwt.refreshToken.expiry=864000000
authentication.jwt.token.endpoint=

# Security Config
security.protected-urls=/secure/**, /api/private/**
security.unprotected-urls=/api/auth/**, /login, /public/**, /api/auth/refresh, /userProfiles, /userProfiles/**, /users/verify-account, /users/regenerate-code, /users/login, /users/forgot-password, /users/set-password