spring.datasource.url=jdbc:mariadb://localhost:3306/workflow
spring.datasource.username=workflow
spring.datasource.password=C3586C92611157ED681FF05170496815
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.springframework=DEBUG

#Configure application context
server.servlet.context-path=/apis

cors.allowedOrigins=http://localhost:3000
cors.allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#cors.allowedHeaders=Accept,Authorization,Content-Type
cors.allowedHeaders=*
cors.allowCredentials=true
cors.maxAge=600
